language: python
python:
  - "2.7"

sudo: false
cache: pip

install:
  # not tracking upstream: change version if/when required
  - pip install doc8==0.8.0

script:
  # we ignore D001 (Line too long) as REPs rely on (soft) wrapping in
  # editors / viewers.
  - "doc8 --file-encoding=utf8 --ignore D001 *.rst"
