language: python
python:
  - "2.7"

sudo: false
cache: pip

install:
  # not tracking upstream: change version if/when required
  - pip install doc8==0.8.0

script:
  - "doc8 --file-encoding=utf8 *.rst"
